# ─ traffic_project/eval/eval_config.yaml ────

batch: 8
tensor_dir: "3_tensor"

ckpt:
  lstm:      "ckpts_lstm/lstm_epoch040.pt"
  stgcn:     "ckpts_stgcn/stgcn_epoch040.pt"
  gated:     "ckpts_gated/gated_epoch040.pt"   # resstgcn → gated 으로 키 변경

# (선택) 에폭별 분석을 할 경우
epoch_list: [5, 10, 15, 20, 25, 30, 35, 40]
ckpt_tpl_lstm:  "ckpts_lstm/lstm_epoch{epoch:03d}.pt"
ckpt_tpl_stgcn: "ckpts_stgcn/stgcn_epoch{epoch:03d}.pt"
ckpt_tpl_gated: "ckpts_gated/gated_epoch{epoch:03d}.pt"   # resstgcn → gated

# Gated 모델 초기화에 필요한 파라미터
hidden1: 64      # --hidden1 에 설정한 값과 일치
hidden2: 128     # --hidden2 에 설정한 값과 일치
use_tcn: false   # TCN 브랜치 사용 시 true

compare_node: 1212
node_list: [1212]

# run_eval.py 가 덮어쓰는 save_dir 은 null 로 두셔도 됩니다.
save_dir: null