# ─ traffic_project/eval/eval_config.yaml ────

batch: 8
tensor_dir: "3_tensor"

ckpt:
  lstm:      "ck_lstm/lstm_ep040.pt"
  stgcn:     "ck_stgcn/stgcn_ep040.pt"
  pooled:    "ck_pooled/pooled_ep040.pt"

# (선택) 에폭별 분석을 할 경우
epoch_list: [5, 10, 15, 20, 25, 30, 35, 40]
ckpt_tpl_lstm:  "ck_lstm/lstm_ep{epoch:03d}.pt"
ckpt_tpl_stgcn: "ck_stgcn/stgcn_ep{epoch:03d}.pt"
ckpt_tpl_pooled: "ck_pooled/pooled_ep{epoch:03d}.pt"

# Gated 모델 초기화에 필요한 파라미터
hidden1: 64      # STGCN hidden dimension
hidden2: 128     # (unused for pooled)
use_tcn: false   # (unused for pooled)
hidden_lstm: 256 # PooledResSTGCN Cluster-LSTM hidden
cluster_map: "segment/lane_to_segment_id_by_edge.npy"

compare_node: 1212
node_list: [1212]

# run_eval.py 가 덮어쓰는 save_dir 은 null 로 두셔도 됩니다.
save_dir: null